### ISSUE TITLE
Termix will not start

### ISSUE THREAD

**Issue by jdawes** [Termix-SSH/Support#182]
Looks like there is something wrong with starting database:

docker logs termix
Migration attempt 1 of 3
Checking MongoDB version...
Starting MongoDB 4.4...
Waiting for MongoDB to start...
Waiting for MongoDB... (attempt 1/30)
/entrypoint.sh: line 103:    10 Illegal instruction     (core dumped) gosu mongodb /usr/bin/mongod --dbpath $MONGODB_DATA_DIR --logpath $MONGODB_LOG_DIR/mongodb.log --bind_ip 0.0.0.0
Waiting for MongoDB... (attempt 2/30)
Waiting for MongoDB... (attempt 3/30)
Waiting for MongoDB... (attempt 4/30)
Waiting for MongoDB... (attempt 5/30)

Using docker compose from this page:
https://github.com/LukeGus/Termix/wiki/Docker

```
services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - mongodb-data:/data/db
    environment:
      # Generate random salt here https://www.lastpass.com/features/password-generator (max 32 characters, include all characters for settings)
      SALT: "2v.F7!6a!jIzmJsu|[)h61$ZMXs;,i+~"

volumes:
  mongodb-data:
    driver: local
```
